const POINT_ORDER = { Hard: 0, Medium: 1, Easy: 2 };

const categories = [
  {
    category: 'Harry, Friends & Families',
    short: 'Harry Friends',
    accent: '#8b3f2f',
    questions: [
      ['How many presents did Dudley think he received on his birthday?', '36', 'Easy'],
      ['Who first visits Harry and Ron in their train compartment?', 'Fred and George', 'Medium'],
      ['What "joke" does Harry interrupt Uncle Vernon from completing during the dinner party?', 'Japanese Golfer Joke', 'Hard'],
      ['What chore does Mrs. Weasley make Fred, George, and Ron do as punishment for flying the car?', 'De-gnoming the garden', 'Medium'],
      ['What was Percy Weasley\'s secret?', 'He had a girlfriend named Penelope Clearwater and was seen kissing her', 'Medium'],
      ['What prank did Sirius Black pull on Snape when they were students at Hogwarts?', 'Sirius told Snape how to get past the Whomping Willow hoping he would run into Lupin transformed as a Werewolf', 'Hard'],
      ['What did Moody ask of Harry after he saved him from Snape and Filch?', 'He asked to borrow the Marauder\'s Map', 'Hard'],
      ['Who gives Harry the gillyweed?', 'Dobby', 'Easy'],
      ['Who acted as a witness for Harry during his trial at the Ministry of Magic?', 'Arabella Figg', 'Medium'],
      ['What did Tonks get Harry for Christmas?', 'A miniature Firebolt', 'Hard'],
      ['What was Harry\'s witty retort to Snape during their first DADA class that earned him a Saturday detention?', '"There\'s no need to call me \'sir\', Professor."', 'Easy'],
      ['What were Dumbledore\'s last words?', '"Severus...please..."', 'Easy'],
      ['Who was Ginny\'s first boyfriend?', 'Michael Corner', 'Medium'],
      ['What was Ginny\'s biggest worry immediately after she woke up in the Chamber of Secrets?', 'She would be expelled and her parents would be angry', 'Medium'],
      ['Give the correct response: "After all this time?"', '"Always."', 'Easy'],
      ['Who teaches Harry how to cast a Patronus Charm?', 'Remus Lupin', 'Easy'],
      ['What brand of broomstick did Fred and George fly?', 'Cleansweep Five', 'Hard'],
      ['Who does Lee Jordan say is attractive during the Quidditch match?', 'Angelina Johnson', 'Hard'],
    ],
  },
  {
    category: 'Dark Wizards & Secrets',
    short: 'Dark Secrets',
    accent: '#39445f',
    questions: [
      ['What is the first trap that Harry, Ron, and Hermione have to get passed under the trap door?', 'Devil\'s Snare', 'Easy'],
      ['What book was Harry reading under the covers of his bed at the beginning of Prisoner of Azkaban?', 'A History of Magic', 'Hard'],
      ['Who is revealed to have stolen the passwords to get into Gryffindor Tower from Neville\'s bedside table?', 'Crookshanks', 'Medium'],
      ['How many turns did Hermione and Harry turn the Time-Turner to go back in time in order to save Sirius?', 'Three turns', 'Medium'],
      ['What was James Potter\'s Animagus form?', 'A Stag', 'Easy'],
      ['What did Voldemort use as nourishment while staying in Riddle House with Wormtail?', 'Nagini\'s Milk', 'Hard'],
      ['During which O.W.L exam did Harry have his vision?', 'History of Magic', 'Medium'],
      ['What was in the package that Sirius gave to Harry?', 'A two-way mirror', 'Easy'],
      ['How did Narcissa ensure Snape would protect Draco throughout the year?', 'She made him make the Unbreakable Vow', 'Medium'],
      ['What grade did Harry get in his O.W.L. for Defense Against the Dark Arts?', 'Outstanding (O)', 'Medium'],
      ['What was Dumbledore\'s theory on how Merope and Tom Riddle Sr. became a couple?', 'Merope used a love potion on him', 'Hard'],
      ['Which of these items did Voldemort steal while he was a kid living at the orphanage?', 'A mouth organ', 'Hard'],
      ['What did Voldemort request of Dumbledore years prior in his office?', 'To become a teacher at Hogwarts', 'Medium'],
      ['Why was Albus Dumbledore already notorious as an eleven-year-old on his first day at Hogwarts?', 'His father, Percival, had been convicted of attacking Muggles and was sent to Azkaban', 'Hard'],
      ['What did Auntie Muriel reveal about Ariana, Dumbledore\'s sister, during the wedding?', 'She was a squib', 'Hard'],
      ['How many pieces does Voldemort divide his soul into, including himself?', 'Seven', 'Easy'],
      ['Where do the Dursleys live?', '4 Privet Drive', 'Easy'],
      ['Which planet do Ronan and Bane remark is bright that night in the Forbidden Forest?', 'Mars', 'Medium'],
      ['Besides Dumbledore, who else drank the potion in the Horcrux Cave?', 'Regulus Black', 'Hard'],
      ['Which character is killed by the basilisk in Harry Potter and the Chamber of Secrets?', 'Moaning Myrtle', 'Easy'],
      ['Who was the headmaster of Hogwarts when the Chamber of Secrets was opened for the first time?', 'Professor Armando Dippet', 'Hard'],
    ],
  },
  {
    category: 'Hogwarts & Student Life',
    short: 'Student Life',
    accent: '#7b5f2a',
    questions: [
      ['On which day does the first term of Hogwarts start?', 'September 1st', 'Easy'],
      ['Who teaches History of Magic?', 'Professor Binns', 'Easy'],
      ['How many total extra points does Dumbledore give the Gryffindor\'s at the end of the term feast?', '170', 'Medium'],
      ['What was the password to enter the Gryffindor Common Room in the second year?', 'Wattlebird', 'Medium'],
      ['Who is revealed to have stolen the passwords to get into Gryffindor Tower from Neville\'s bedside table?', 'Crookshanks', 'Hard'],
      ['Which house was Dennis Creevey sorted into?', 'Gryffindor', 'Medium'],
      ['What does Professor Moody say during his class that everyone needs above all else?', 'Constant vigilance', 'Hard'],
      ['What did Professor Umbridge force Harry to write during his detention?', '"I must not tell lies"', 'Medium'],
      ['Who became the new Divination teacher after Professor Trelawney was sacked?', 'The centaur Firenze', 'Hard'],
      ['How did the Death Eaters recognize Harry during his flight with Hagrid to the safehouse?', 'Harry used his signature move, Expelliarmus during the battle', 'Hard'],
      ['What does Harry use to survive underwater during the Second Task of the Triwizard Tournament?', 'Gillyweed', 'Medium'],
      ['How many staircases does Hogwarts have?', '142', 'Hard'],
      ['What is the name of the room Harry uses to teach Dumbledore\'s Army?', 'Room of Requirement', 'Easy'],
      ['What is the name of the book Hermione supposes Voldemort used to learn about Horcruxes?', 'Secrets of the Darkest Art', 'Medium'],
      ['Which Hogwarts professor was rumoured to be a duelling champion in their youth?', 'Professor Filius Flitwick', 'Hard'],
      ['Who is the Hufflepuff house ghost?', 'Fat Friar', 'Easy'],
      ['Who found the petrified Colin Creevey', 'Professor McGonagall', 'Medium'],
      ['In order they taught, who were the six Defence Against the Dark Arts professors who taught Harry at Hogwarts?', 'Quirinus Quirrell, Gilderoy Lockhart, and Remus Lupin', 'Hard'],
      ['Who is named Minister of Magic after the Battle of Hogwarts in Harry Potter and the Deathly Hallows?', 'Kingsley Shaklebolt', 'Medium'],
    ],
  },
  {
    category: 'Magic and Spells',
    short: 'Magic Spells',
    accent: '#6d4a96',
    questions: [
      ['What spell does Malfoy use on Neville to bully him?', 'Locomotor Mortis', 'Medium'],
      ['What was the first spell Harry used against Malfoy during the dueling club?', 'Rictusempra', 'Easy'],
      ['What curse was used on Neville Longbottom\'s parents?', 'Cruciatus Curse', 'Easy'],
      ['What was written in the Howler sent to Aunt Petunia?', '"Remember my last, Petunia"', 'Hard'],
      ['What spell did Hermione suggest to use in order for Dumbledore\'s Army to know the time and date of their meetings?', 'Protean Charm', 'Hard'],
      ['What are the three most important things to remember when Apparating?', 'Destination, Determination, Deliberation', 'Medium'],
      ['According to Tom Riddle, what is the most powerfully magical number?', 'Seven', 'Medium'],
      ['Who is revealed to have been placed under the Imperius Curse by Draco Malfoy?', 'Rosmerta', 'Hard'],
      ['What is the first of the five Principal Exceptions to Gamp\'s Law of Elemental Transfiguration?', 'Food', 'Hard'],
      ['Who destroyed the Locket Horcrux?', 'Ron Weasley', 'Easy'],
      ['What is the final spell Harry used against Voldemort?', 'Expelliarmus', 'Easy'],
      ['The Sorting Hat considers which two houses for Harry before ultimately choosing Gryffindor?', 'Slytherin and Gryffindor', 'Easy'],
      ['Which spell is used to summon items, even from across the room?', 'Accio', 'Easy'],
      ['Who is named Minister of Magic after the Battle of Hogwarts in Harry Potter and the Deathly Hallows?', 'Kingsley Shaklebolt', 'Medium'],
      ['How do Harry and Ron get to Hogwarts after they miss the last Hogwarts Express in Harry Potter and the Chamber of Secrets?', 'Flying car', 'Easy'],
      ['Slughorn teaches his students that Amortentia smells different to each person. What food does Harry smell?', 'Treacle tart', 'Medium'],
      ['Which charm prevents eavesdropping by creating an invisible barrier around a conversation?', 'Muffliato', 'Hard'],
      ['What spell does Hermione use to enlarge her beaded handbag?', 'Undetectable Extension Charm', 'Hard'],
      ['What spell causes a wand to reveal its most recent spell?', 'Prior Incantato', 'Medium'],
    ],
  },
  {
    category: 'Magical Creatures',
    short: 'Creatures',
    accent: '#427c70',
    questions: [
      ['What type of creature did Gilderoy Lockhart let loose on his class?', 'Cornish pixies', 'Easy'],
      ['What was Aragog\'s wife\'s name?', 'Mosag', 'Hard'],
      ['What animal did Hermione buy at the magical pet shop?', 'A cat', 'Easy'],
      ['Who was the previous Care of Magical Creatures teacher before Hagrid took over the role?', 'Professor Kettleburn', 'Medium'],
      ['What was the name of the Hippogriff Harry bonded with?', 'Buckbeak', 'Easy'],
      ['Who replaced the Fat Lady as the Gryffindor Common Room entrance portrait?', 'Sir Cadogan', 'Medium'],
      ['Who or what did Hermione\'s boggart turn into during her final Defense Against the Dark Arts exam?', 'Professor McGonagall', 'Medium'],
      ['What were the Bulgarian National Quidditch Team mascots?', 'Veela', 'Medium'],
      ['What was the name of the secret radio show hosted by Lee Jordan?', 'Potterwatch', 'Hard'],
      ['What was the answer to the Ravenclaw Dorm Riddle: "Which came first, the phoenix or the flame?"', 'A circle has no beginning', 'Hard'],
      ['What type of creature is Dobby?', 'House Elf', 'Easy'],
      ['Dumbledore\'s pet phoenix is named?', 'Fawkes', 'Easy'],
      ['Which creatures pull the carriages that take students from the Hogwarts Express to the Castle?', 'Thestrals', 'Medium'],
    ],
  },
];

export const HARRY_POTTER_BOOK_QUESTION_DATA = categories.map((category) => ({
  ...category,
  questions: category.questions
    .map(([question, answer, difficulty], index) => ({ question, answer, difficulty, id: `${category.short}-${index}` }))
    .sort((first, second) => POINT_ORDER[first.difficulty] - POINT_ORDER[second.difficulty]),
}));

export const HARRY_POTTER_QUESTION_DATA = HARRY_POTTER_BOOK_QUESTION_DATA;
